### ISSUE TITLE
logo is reaching into the title as soon as you have a small window

### ISSUE THREAD

**Issue by ultraschuppi** [camunda-cloud/camunda-cloud-docs#24]
![image](https://user-images.githubusercontent.com/6298245/77167306-11983000-6ab6-11ea-9076-c6e8b806e888.png)

found by @mary-grace

**Comment by urbanisierung** [comment]
fixed by shortening the title to `Camunda Cloud Docs` - the framework does the rest

thx for the hint @mary-grace!
